### ISSUE TITLE
Замечание (02.10.19)

### ISSUE THREAD

**Issue by aprogrom** [Pe1me4ka/Zakharov-s-repository#1]
а где проект нулевой лабы?

**Comment by Pe1me4ka** [comment]
@aprogrom Смысл? Это ведь просто Hello world. Первую лабу уже собираюсь закинуть проектом

**Comment by aprogrom** [comment]
Потому что задание звучало как создать репозиторий, закинуть на него пустой проект и добавить меня наблюдающим. И тут важно понимать, это как на работе, вы можете сколько угодно думать что что то бред, пытаться переубедить руководство(в данном случае меня) в том что его задача неправильная, но все равно обязаны сделать её до тех пор пока вам не скажут что это не нужно, так и выглядят рабочие отношения(учеба это частный их случай так как учёба это работа ученика), мы можем сколько угодно весело и неформально общаться хоть на парах хоть вне их, но если задание звучит так значит его нужно сделать так. Это задание показывает что вы владеете азами взаимодействия с гит и с иде. В этом его суть и оценивается оно исходя из этого.

**Comment by Pe1me4ka** [comment]
@aprogrom Понял суть, перезалил

**Comment by aprogrom** [comment]
@Pe1me4ka я возможно слишком резко написал, просто если есть задание его нужно выполнить. Молодцы что перезалили.
